spring:
  profiles:
    active: pord
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: d9d2j9w2
    driver-class-name: com.mysql.cj.jdbc.Driver
    resources:
      add-mappings: true
  activiti:
    check-process-definitions: true
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/
    database-schema: activiti